apiVersion: v2
name: notification-service
description: notification-service for e-commerce platform
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: microservices-base-chart
    version: "1.0.0"
    repository: "file://../../../microservices-base-chart"
maintainers:
  - name: Platform Team
    email: platform@example.com
